table ARTICOLI
	lineageTag: 62754965-7765-408c-87d0-aa6b81d68817

	column ItemCode
		dataType: string
		lineageTag: d739b2eb-1550-41f9-852d-61be42f6d751
		summarizeBy: none
		sourceColumn: Item Code

		annotation SummarizationSetBy = Automatic

		annotation Description = "Primary product identifier. Unique SKU or article number. Proposed – pending Loro Piana validation."

		annotation Synonyms = "Product Code, Article Number, SKU, Style Code"

		annotation DisplayFolder = "Product Identification"

	column BusinessCode
		dataType: string
		lineageTag: 5246a7be-f520-4435-ba8f-b25d6224bf4f
		summarizeBy: none
		sourceColumn: Business Code

		annotation SummarizationSetBy = Automatic

		annotation Description = "Business-facing product code used in commercial systems. Proposed – pending Loro Piana validation."

		annotation Synonyms = "Commercial Code, Trading Code"

		annotation DisplayFolder = "Product Identification"

	column CategoryCode
		dataType: string
		lineageTag: 38a85d2a-9c01-4a5f-bd82-921c4a78b84e
		summarizeBy: none
		sourceColumn: Category Code

		annotation SummarizationSetBy = Automatic

		annotation Description = "Product category code at the highest classification level (e.g., 'RTW' for Ready-to-Wear, 'ACC' for Accessories). Proposed – pending Loro Piana validation."

		annotation Synonyms = "Category, Product Category, Merchandise Category"

		annotation DisplayFolder = "Product Classification"

	column SubCategoryCode
		dataType: string
		lineageTag: f0e761ad-a564-4511-a307-5861f64b17ae
		summarizeBy: none
		sourceColumn: Sub Category Code

		annotation SummarizationSetBy = Automatic

		annotation Description = "Product sub-category code providing finer classification within the category (e.g., 'DRS' for Dresses, 'SHP' for Shoes). Proposed – pending Loro Piana validation."

		annotation Synonyms = "Sub-Category, Product Sub-Category"

		annotation DisplayFolder = "Product Classification"

	column ItemDescription
		dataType: string
		lineageTag: 4452aba8-bb9d-444a-8f43-8eeec7fdbc77
		summarizeBy: none
		sourceColumn: Item Description

		annotation SummarizationSetBy = Automatic

		annotation Description = "Full product description including name, style, and key attributes. Used for reporting and dashboard labels. Proposed – pending Loro Piana validation."

		annotation Synonyms = "Product Name, Description, Item Name"

		annotation DisplayFolder = "Product Identification"

	column FamilyCode
		dataType: string
		lineageTag: 5a696f9b-0bed-4090-8902-d7f604bebeb4
		summarizeBy: none
		sourceColumn: Family Code

		annotation SummarizationSetBy = Automatic

		annotation Description = "Product family code grouping products within a category (e.g., 'KNIT' for Knitwear, 'WOVEN' for Woven items). Proposed – pending Loro Piana validation."

		annotation Synonyms = "Family, Product Family"

		annotation DisplayFolder = "Product Classification"

	column GenderCode
		dataType: string
		lineageTag: fca23489-c549-409e-b483-6a23d14b9093
		summarizeBy: none
		sourceColumn: Gender Code

		annotation SummarizationSetBy = Automatic

		annotation Description = "Product gender classification. Allowed values likely: 'M' (Men), 'W' (Women), 'U' (Unisex). Proposed – pending Loro Piana validation."

		annotation Synonyms = "Gender, Product Gender"

		annotation DisplayFolder = "Product Classification"

	column CitesCode
		dataType: string
		lineageTag: 90505c89-34ae-40d4-8b73-ff18c23cdcaa
		summarizeBy: none
		sourceColumn: Cites Code

		annotation SummarizationSetBy = Automatic

		annotation Description = "CITES (Convention on International Trade in Endangered Species) product classification. Indicates if product uses protected materials requiring documentation. Proposed – pending Loro Piana validation."

		annotation Synonyms = "CITES, Endangered Species Classification"

		annotation DisplayFolder = "Product Classification"

	column CommercialModelCode
		dataType: string
		lineageTag: ec2c1fcf-e2c6-4a87-9ab7-67c3d75caf61
		summarizeBy: none
		sourceColumn: Commercial Model Code

		annotation SummarizationSetBy = Automatic

		annotation Description = "Commercial model classification for product pricing and distribution strategy (e.g., 'B2C', 'B2B', 'WHL' for Wholesale). Proposed – pending Loro Piana validation."

		annotation Synonyms = "Commercial Model, Sales Model, Distribution Model"

		annotation DisplayFolder = "Commercial Attributes"

	column SalesCategoryCode
		dataType: string
		lineageTag: 566297d9-9661-4314-b6e3-f0dbb3424495
		summarizeBy: none
		sourceColumn: Sales Category Code

		annotation SummarizationSetBy = Automatic

		annotation Description = "Sales-focused product categorization used for revenue reporting and performance analysis. Proposed – pending Loro Piana validation."

		annotation Synonyms = "Sales Category, Revenue Category"

		annotation DisplayFolder = "Commercial Attributes"

	column CommercialFamilyCode
		dataType: string
		lineageTag: 87a0e2ea-09de-488e-bb1f-d74891a65239
		summarizeBy: none
		sourceColumn: Commercial Family Code

		annotation SummarizationSetBy = Automatic

		annotation Description = "Commercial family grouping products by market positioning and pricing strategy. Proposed – pending Loro Piana validation."

		annotation Synonyms = "Commercial Family, Market Family"

		annotation DisplayFolder = "Commercial Attributes"

	column StageOfLifeCode
		dataType: string
		lineageTag: ab7badf0-4214-4667-a6be-d6dc38797d34
		summarizeBy: none
		sourceColumn: Stage of Life Code

		annotation SummarizationSetBy = Automatic

		annotation Description = "Product lifecycle stage code (e.g., 'NEW' for current season, 'OLD' for prior season, 'DIS' for discontinued). Proposed – pending Loro Piana validation."

		annotation Synonyms = "Lifecycle Stage, Product Stage"

		annotation DisplayFolder = "Product Classification"

	partition ARTICOLI = m
		mode: import
		source =
				let
				        Source = PowerPlatform.Dataflows(null),
				        Workspaces = Source{[Id="Workspaces"]}[Data],
				        WS = Workspaces{[workspaceId="63075e43-ec19-4090-b204-854337b4b0d5"]}[Data],
				        DF = WS{[dataflowId="dcbf1499-ee35-4598-9b58-2d0142058031"]}[Data],
				        ARTICOLI1 = DF{[entity="ARTICOLI"]}[Data],
				        #"Rimosse altre colonne" = Table.SelectColumns(ARTICOLI1,{"Item Code", "Business Code", "Category Code", "Sub Category Code", "Item Description","Family Code", "Gender Code", "Cites Code", "Commercial Model Code", "Sales Category Code","Commercial Family Code", "Stage of Life Code"})
				in
				        #"Rimosse altre colonne"

		annotation Description = "Import partition for product master data. Loads all products without date filtering."

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

	annotation Description = "Product master data dimension. Contains all product attributes including codes, descriptions, and classification hierarchies (category, sub-category, family, etc.). Grain: one row per product. Proposed – pending Loro Piana validation."

	annotation Synonyms = "Products, Items, Merchandise, Article, SKU"

	annotation DisplayFolder = "Product Master"

	annotation RefreshPolicy = "Weekly on Sundays at 00:00 UTC; data latency ≤ 48 hours. Proposed – pending Loro Piana validation."

	annotation BusinessOwner = "Loro Piana Product Management Team. Proposed – pending validation."

	annotation CertificationStatus = "Certified by BI Team on 2026-08-06 (pending business sign-off)."
